### PR TITLE
Use HTTPS URLs

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by sdushantha** [comment]
Thank you for fixing that! 👍

**Comment by sdushantha** [comment]
@leonklingele Not sure why, but adding HTTPS seems to break the script. Curl does not return anything when HTTPS is used. 
I have changed back to HTTP in the script for now. I'll need to look further into this later

**Comment by leonklingele** [comment]
@sdushantha the issue seems to occur whenever a TLD other than `com` is used as its certificate is only valid for `1secmail.com`:

```sh
$ ./tmpmail
https://1secmail.net/api/v1/?action=getMessages&login=cdqvhfvtnyv&domain=1secmail.net
*   Trying 178.32.61.35:443...
* Connected to 1secmail.net (178.32.61.35) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl@1.1/cert.pem
  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=1secmail.com
*  start date: Sep  1 02:12:04 2020 GMT
*  expire date: Nov 30 02:12:04 2020 GMT
*  subjectAltName does not match 1secmail.net
* SSL: no alternative certificate subject name matches target host name '1secmail.net'
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name '1secmail.net'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ Inbox for cdqvhfvtnyv@1secmail.net ]

./tmpmail: line 131: [: : integer expression expected
seq: invalid floating point argument: ''
Try 'seq --help' for more information.
```

**Comment by leonklingele** [comment]
Proper fix is in https://github.com/sdushantha/tmpmail/pull/7

**Pull request merged**
