### PR TITLE
Format code using `shfmt`

### PR DESCRIPTION
**Pull request by vladimyr**
Introducing `.editorconfig` with [`shfmt`](https://github.com/mvdan/sh#shfmt) configuration.

### CODE REVIEW

**Comment by vladimyr** [comment]
Changes are the result of running `shfmt -w tmpmail`.

**Comment by sdushantha** [comment]
I like the changes you made to the formatting of the code using `shfmt`, but I dont want to add the `.editorconfig` as it is IDE specific.

If you remove `.editorconfig` and fix the conflicts, I think this PR should be good to be merged.

**Comment by vladimyr** [comment]
The sole point of `.editorconfig` is to be editor agnostic as opposed to having separate vim, emacs, vscode, IntelliJ, you name it configs 😉
In this case, it also holds `shmft` settings so if I remove it any subsequent `shfmt` invocation has to use the exact same flags and that is error-prone and basically yells - Add a makefile 😉

Regarding conflicts, sure, I'll do my homework.

**Comment by sdushantha** [comment]
> The sole point of `.editorconfig` is to be editor agnostic as opposed to having separate vim, emacs, vscode, IntelliJ, you name it configs 😉

Ah okay. Sorry, I dont know much about the `.editorconfig` file, but now I see that is reasonable to include it.

**Comment by vladimyr** [comment]
Conflicts resolved ✅

**Comment by sdushantha** [comment]
Awesome! Thank you :)

**Pull request merged**
