### PR TITLE
Change to add Ubuntu deps install command

### PR DESCRIPTION
**Pull request by ThomasG77**
The `gawk` addition in the proposed command can be discussed in my PR as there is already a default installed awk version e.g https://askubuntu.com/a/710381

### CODE REVIEW

**Comment by sdushantha** [comment]
Okay, so from my understanding Ubuntu already has a version of `awk` called `mawk`. But `gawk`, which is the GNU version as more features. 

Is `gawk` needed for `tmpmail` to work?

**Comment by rpdelaney** [comment]
> Is `gawk` needed for `tmpmail` to work?

No: https://ideone.com/Tnhhj7

**Comment by ThomasG77** [comment]
Made change in the PR to remove refs to `gawk`

**Comment by sdushantha** [comment]
@rpdelaney Thank you for informing us

@ThomasG77 
I'm not sure I want to add these changes to the README. 
In my opinion, if someone wants to use `tmpmail`, they should atleast know how to install the dependencies that have been listed in the README. If for some reason the user does not know how install packages on their system, they can easly find out by doing a quick Google search. 

Another why I don't want to add the command to install the dependencies for Ubuntu in the README is because I would the have to list the command to install the dependencies for all *nix systems so that they too know how to install the dependencies. I don't want to fill the whole README with commands to install packages.

Hope that makes sense.

**Comment by ThomasG77** [comment]
No problem. You are the maintainer. People will pick up the info from this PR otherwise.

**Pull request closed without merging**
