### PR TITLE
feat: allow command line flags to be used in any order

### LINKED ISSUE #1: Allow command line flags to be used in any order
At the moment the flags have to be in a certain order.
For example if I want to view the most recent email and want the output to be as raw text, I have to run `tmpmail --text --recent` for it work properly. Running `tmpmail --recent --text` will ignore the `--text` flag.

By allowing the flags to be used in any order would make it much easier to use.

### PR DESCRIPTION
**Pull request by zanona**
This PR allows using option arguments in any position by depending on `getopt`

resolve #1

### CODE REVIEW

**Comment by sdushantha** [comment]
Thank you! I really appreciate you attempting to fix this!

It looks like there is something wrong. `tmpmail` fails to show the help message when the `--help` flag is used
image

**Comment by zanona** [comment]
Hi!
That's strange. I've notice you are invoking `tmpmail` from your `PATH` there, which may be aliased to a different version of the program.

Do you get the same when running `bash ./tmpmail --help` from the project directly?

you can also do from the project directory:
```sh
alias tmpmail=./tmpmail
bash tmpmail --help
```

**Comment by sdushantha** [comment]
Non of the solutions that you have suggested fixes the issue
Screenshot 2020-11-11 at 17 08 56

**Comment by zanona** [comment]
Ah, I believe we have a compatibility issue here, where `getopt` OSX implementation doesn't support long names.

https://stackoverflow.com/questions/12152077
> BSD UNIX implementation of standalone getopt command (which is what MacOS uses). This does not support long options either.

Apologies for having missed this previously as it works well on Linux.
I am going to close this now so if someone would like to implement this use `getopts` with a hack for long names instead, that should be cross compatible.

**Pull request closed without merging**
